# Generated by Django 2.2.3 on 2019-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='use_gravatar',
            field=models.BooleanField(blank=True, default=False, verbose_name='Use Avatars from Gravatar?'),
        ),
    ]
