# Generated by Django 2.2.3 on 2019-07-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_board_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='subboards', to='boards.Board'),
        ),
    ]
